---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ca
  labels:
    run: blockchain-ca
spec:
  type: NodePort
  selector:
    name: ca
  ports:
  - protocol: TCP
    port: 7054
    nodePort: 30000
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer
  labels:
    run: blockchain-orderer
spec:
  type: NodePort
  selector:
    name: orderer
  ports:
  - protocol: TCP
    port: 31010
    nodePort: 31010
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org1peer1
  labels:
    run: blockchain-org1peer1
spec:
  type: NodePort
  selector:
    name: org1peer1
  ports:
  - protocol: TCP
    port: 5010
    nodePort: 30110
    name: grpc
  - protocol: TCP
    port: 5011
    nodePort: 30111
    name: events
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-couchdb1
  labels:
    run: blockchain-couchdb1
spec:
  type: NodePort
  selector:
    name: couchdb1
  ports:
  - protocol: TCP
    port: 5984
    nodePort: 30984
    name: couchdb1
